# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5
      - image: redis:4.0.6

    working_directory: ~/seneca

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Dockerize v0.6.0
          command: |
            wget https://github.com/jwilder/dockerize/releases/download/v0.6.0/dockerize-linux-amd64-v0.6.0.tar.gz
            sudo rm -rf /usr/local/bin/dockerize
            sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.0.tar.gz
            rm dockerize-linux-amd64-v0.6.0.tar.gz

      - run:
          name: Install Twine
          command: |
            sudo pip3 install twine

      - run:
          name: install dependencies
          command: |
            sudo pip install -r requirements.txt
            sudo pip install -r dev-requirements.txt

      - run:
          name: Build C-extensions
          command: |
            sudo python3 setup.py build_ext -i
            sudo python3 setup.py install

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Wait for Redis
          command: |
            dockerize -wait tcp://localhost:6379 -timeout 2m

      - run:
          name: run tests
          command: |
            export PYTHONPATH=$PYTHONPATH:$(pwd):~/seneca
            python3 tests/run.py

      - run:
          name: Upload to PyPI
          command: |
            bash scripts/upload_pip.sh

  test-cilantro-from-seneca:
    docker:
      - image: circleci/python:3.6.5
    working_directory: ~/src/lamden/seneca

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          name: Test Cilantro
          command: |
            pip3 install requests
            echo "Testing Cilantro using Seneca Branch $CIRCLE_BRANCH"
            python3 scripts/cilantro_tester.py --seneca_branch $CIRCLE_BRANCH

workflows:
  version: 2
  seneca_tests:
    jobs:
      - build
      # - test-cilantro-from-seneca
